In [2]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [6]:
l = ([[1, 2,3],[4,5,6], [7,8,9]])
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
arr = np.array(l)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
